#[cfg(test)]
mod tests {
    use crate::models::class::NewHubuumClass;
    use crate::traits::CanSave;
    use actix_web::{http, test};

    use crate::assert_contains_all;
    use crate::tests::api_operations::get_request;
    use crate::tests::asserts::assert_response_status;
    use crate::tests::constants::{get_schema, SchemaType};
    use crate::tests::{create_namespace, setup_pool_and_tokens};

    const CLASSES_ENDPOINT: &str = "/api/v1/classes";

    async fn create_test_classes(prefix: &str) -> Vec<crate::models::class::HubuumClass> {
        let (pool, _, _) = setup_pool_and_tokens().await;

        let ns = create_namespace(&pool, &format!("{}_{}", prefix, "api_create_test_classes"))
            .await
            .unwrap();

        let mut created_classes = vec![];

        for i in 0..4 {
            let schema = if i == 4 {
                get_schema(SchemaType::Geo).clone()
            } else if i > 2 {
                get_schema(SchemaType::Address).clone()
            } else {
                get_schema(SchemaType::Blog).clone()
            };

            let class = NewHubuumClass {
                name: format!("{}_api_class_{}", prefix, i),
                description: format!("{}_api_description_{}", prefix, i),
                namespace_id: ns.id,
                json_schema: schema,
                validate_schema: false,
            };

            created_classes.push(class.save(&pool).await.unwrap());
        }
        created_classes
    }

    #[actix_web::test]
    async fn test_api_classes_get() {
        let created_classes = create_test_classes("get").await;

        let (pool, admin_token, _) = setup_pool_and_tokens().await;

        let resp = get_request(&pool, &admin_token, CLASSES_ENDPOINT).await;

        let resp = assert_response_status(resp, http::StatusCode::OK).await;
        let classes: Vec<crate::models::class::HubuumClass> = test::read_body_json(resp).await;

        // We can't do
        // assert_eq!(classes.len(), created_classes.len());
        // As we may have other classes generated by other tests
        assert_contains_all!(&classes, &created_classes);
    }

    #[actix_web::test]
    async fn test_api_classes_get_filtered() {
        let created_classes = create_test_classes("get_filtered").await;

        let (pool, admin_token, _) = setup_pool_and_tokens().await;

        let query_string = format!("name={}", created_classes[0].name);
        let resp = get_request(
            &pool,
            &admin_token,
            &format!("{}?{}", CLASSES_ENDPOINT, query_string),
        )
        .await;

        let resp = assert_response_status(resp, http::StatusCode::OK).await;
        let classes: Vec<crate::models::class::HubuumClass> = test::read_body_json(resp).await;

        assert_eq!(classes.len(), 1);
        assert_eq!(classes[0].name, created_classes[0].name);
    }
}
