#[cfg(test)]
pub mod tests {
    use std::time::Duration;

    use crate::db::prelude::*;
    use crate::db::with_transaction;
    use crate::errors::ApiError;
    use crate::events::EventContext;
    use crate::models::traits::{ResolveClassTarget, UpdateResolvedClass};
    use crate::models::{
        ClassSelector, HubuumClassExpanded, HubuumClassID, NewHubuumClass, Permissions,
        PermissionsList, UpdateHubuumClass,
    };
    use crate::traits::{CanSave, PermissionController, SelfAccessors};
    use actix_web::{http::StatusCode, test};

    use rstest::rstest;

    use crate::pagination::{NEXT_CURSOR_HEADER, TOTAL_COUNT_HEADER};
    use crate::tests::api_operations::{delete_request, get_request, patch_request, post_request};
    use crate::tests::asserts::{assert_response_status, header_value};
    use crate::tests::constants::{SchemaType, get_schema};
    use crate::tests::{
        TestContext, cleanup_test_classes as cleanup, create_class_fixture, create_test_classes,
        create_test_group, test_context,
    };
    use crate::{assert_contains_all, assert_contains_same_ids};

    const CLASSES_ENDPOINT: &str = "/api/v1/classes";

    async fn api_get_classes_with_query_string(
        context: &TestContext,
        query_string: &str,
    ) -> Vec<HubuumClassExpanded> {
        let resp = get_request(
            &context.pool,
            &context.admin_token,
            &format!("{CLASSES_ENDPOINT}?{query_string}"),
        )
        .await;

        let resp = assert_response_status(resp, StatusCode::OK).await;
        let classes: Vec<HubuumClassExpanded> = test::read_body_json(resp).await;
        classes
    }

    #[rstest]
    #[actix_web::test]
    async fn test_api_classes_get(#[future(awt)] test_context: TestContext) {
        let context = test_context;
        let created_classes = create_test_classes(&context, "get").await;

        let resp = get_request(&context.pool, &context.admin_token, CLASSES_ENDPOINT).await;
        let resp = assert_response_status(resp, StatusCode::OK).await;
        let classes: Vec<HubuumClassExpanded> = test::read_body_json(resp).await;

        // We can't do
        // assert_eq!(classes.len(), created_classes.len());
        // As we may have other classes generated by other tests (and we're explicitly not filtering on
        // a given collection)
        assert_contains_all!(&classes, &created_classes);

        // Check that we can do api/v1/classes/ as well as api/v1/classes
        let resp = get_request(
            &context.pool,
            &context.admin_token,
            &format!("{CLASSES_ENDPOINT}/"),
        )
        .await;
        let resp = assert_response_status(resp, StatusCode::OK).await;
        let classes: Vec<HubuumClassExpanded> = test::read_body_json(resp).await;
        assert_contains_all!(&classes, &created_classes);
        cleanup(&created_classes).await;
    }

    #[rstest]
    #[actix_web::test]
    async fn missing_class_object_list_preserves_the_empty_page_contract(
        #[future(awt)] test_context: TestContext,
    ) {
        let response = get_request(
            &test_context.pool,
            &test_context.admin_token,
            &format!("{CLASSES_ENDPOINT}/2147483647/"),
        )
        .await;
        let response = assert_response_status(response, StatusCode::OK).await;
        let objects: Vec<serde_json::Value> = test::read_body_json(response).await;

        assert!(objects.is_empty());
    }

    #[rstest]
    #[actix_web::test]
    async fn test_admin_can_list_classes_without_direct_owner_group_membership(
        #[future(awt)] test_context: TestContext,
    ) {
        let context = test_context;
        let collection = context
            .scope
            .collection_fixture("admin_lists_hidden_classes")
            .await;
        let classes = create_class_fixture(
            &context.pool,
            collection,
            vec![
                NewHubuumClass {
                    name: "hidden class a".to_string(),
                    description: "hidden class a".to_string(),
                    collection_id: 0,
                    json_schema: None,
                    validate_schema: Some(false),
                },
                NewHubuumClass {
                    name: "hidden class b".to_string(),
                    description: "hidden class b".to_string(),
                    collection_id: 0,
                    json_schema: None,
                    validate_schema: Some(false),
                },
            ],
        )
        .await
        .unwrap();

        let resp = get_request(
            &context.pool,
            &context.admin_token,
            &format!(
                "{CLASSES_ENDPOINT}?collections={}&sort=id",
                classes.collection.collection.id
            ),
        )
        .await;
        let resp = assert_response_status(resp, StatusCode::OK).await;
        let classes_from_api: Vec<HubuumClassExpanded> = test::read_body_json(resp).await;

        assert_eq!(
            classes_from_api
                .iter()
                .map(|class| class.id)
                .collect::<Vec<_>>(),
            classes.iter().map(|class| class.id).collect::<Vec<_>>()
        );

        cleanup(&classes).await;
    }

    #[rstest]
    #[actix_web::test]
    async fn test_api_classes_get_filtered_name_equals(#[future(awt)] test_context: TestContext) {
        let context = test_context;
        let created_classes = create_test_classes(&context, "get_filtered_name_equals").await;
        let query_string = format!("name={}", created_classes[0].name);
        let classes = api_get_classes_with_query_string(&context, &query_string).await;
        assert_eq!(classes.len(), 1);
        assert_eq!(classes[0].name, created_classes[0].name);
        cleanup(&created_classes).await;
    }

    #[rstest]
    #[actix_web::test]
    async fn test_api_classes_get_filtered_name_contains(#[future(awt)] test_context: TestContext) {
        let context = test_context;
        let created_classes = create_test_classes(&context, "get_filtered_name_contains").await;
        let query_string = "name__contains=get_filtered_name_contains";
        let classes = api_get_classes_with_query_string(&context, query_string).await;
        assert_contains_same_ids!(&classes, &created_classes);
        cleanup(&created_classes).await;
    }

    #[rstest]
    #[actix_web::test]
    async fn test_api_classes_get_filtered_description_contains(
        #[future(awt)] test_context: TestContext,
    ) {
        let context = test_context;
        let created_classes =
            create_test_classes(&context, "get_filtered_description_contains").await;
        let query_string = "description__contains=get_filtered_description_contains";
        let classes = api_get_classes_with_query_string(&context, query_string).await;
        assert_contains_same_ids!(&classes, &created_classes);
        cleanup(&created_classes).await;
    }

    #[rstest]
    #[actix_web::test]
    async fn test_api_classes_get_filtered_description_and_not_name_contains(
        #[future(awt)] test_context: TestContext,
    ) {
        let context = test_context;
        let created_classes =
            create_test_classes(&context, "get_filtered_description_and_not_name_contains").await;
        let query_string = "description__contains=get_filtered_description_and_not_name_contains&name__not_contains=1";
        let classes = api_get_classes_with_query_string(&context, query_string).await;
        assert_eq!(classes.len(), 5);
        cleanup(&created_classes).await;
    }

    #[rstest]
    #[actix_web::test]
    async fn test_api_classes_get_filtered_collections_equals(
        #[future(awt)] test_context: TestContext,
    ) {
        let context = test_context;
        let created_classes =
            create_test_classes(&context, "get_filtered_collections_equals").await;
        let query_string = format!("collections={}", created_classes[0].collection_id);
        let classes = api_get_classes_with_query_string(&context, &query_string).await;
        assert_contains_same_ids!(&classes, &created_classes);
        cleanup(&created_classes).await;
    }

    fn combine_query_string(prefix: &String, query_string: &str) -> String {
        format!("{prefix}&{query_string}")
    }

    #[rstest]
    #[actix_web::test]
    async fn test_api_classes_get_filtered_json_schema(#[future(awt)] test_context: TestContext) {
        let context = test_context;
        let prefix = "get_filtered_classes_json_schema";
        let base_filter = format!("name__contains={prefix}");

        // We have 6 classes, 3 with blog (0,1,2), 2 with address (3,4) and 1 with geo (5)
        let created_classes =
            create_test_classes(&context, "get_filtered_classes_json_schema").await;

        let query_string = combine_query_string(&base_filter, "json_schema__contains=$id=blog");
        let classes = api_get_classes_with_query_string(&context, &query_string).await;
        assert_eq!(classes.len(), 3);
        assert_contains_same_ids!(&classes, &created_classes[0..3]);

        let query_string =
            combine_query_string(&base_filter, "json_schema__contains=description=blog");
        let classes = api_get_classes_with_query_string(&context, &query_string).await;
        assert_eq!(classes.len(), 3);
        assert_contains_same_ids!(&classes, &created_classes[0..3]);

        let query_string =
            combine_query_string(&base_filter, "json_schema__not_contains=description=blog");
        let classes = api_get_classes_with_query_string(&context, &query_string).await;
        assert_eq!(classes.len(), 3);
        assert_contains_same_ids!(&classes, &created_classes[3..6]);

        let query_string = combine_query_string(
            &base_filter,
            "json_schema__lt=properties,latitude,minimum=0",
        );
        let classes = api_get_classes_with_query_string(&context, &query_string).await;
        assert_eq!(classes.len(), 1);
        assert_eq!(&classes[0], &created_classes[5]);

        let query_string =
            combine_query_string(&base_filter, "json_schema=properties,latitude,minimum=-90");
        let classes = api_get_classes_with_query_string(&context, &query_string).await;
        assert_eq!(classes.len(), 1);
        assert_eq!(&classes[0], &created_classes[5]);

        let query_string =
            combine_query_string(&base_filter, "json_schema__contains=required=region");
        let classes = api_get_classes_with_query_string(&context, &query_string).await;
        assert_eq!(classes.len(), 2);
        assert_contains_same_ids!(&classes, &created_classes[3..5]);
        cleanup(&created_classes).await;
    }

    #[rstest]
    #[actix_web::test]
    async fn test_api_classes_json_schema_filter_composes_with_pagination_and_count(
        #[future(awt)] test_context: TestContext,
    ) {
        let context = test_context;
        let prefix = "classes_json_schema_composed";
        let created_classes = create_test_classes(&context, prefix).await;
        let query_string = format!(
            "name__contains={prefix}&json_schema__contains=description=blog&sort=id&limit=2"
        );

        let resp = get_request(
            &context.pool,
            &context.admin_token,
            &format!("{CLASSES_ENDPOINT}?{query_string}"),
        )
        .await;
        let resp = assert_response_status(resp, StatusCode::OK).await;

        let total_count =
            header_value(&resp, TOTAL_COUNT_HEADER).and_then(|value| value.parse::<i64>().ok());
        assert_eq!(total_count, Some(3));
        assert!(header_value(&resp, NEXT_CURSOR_HEADER).is_some());

        let classes: Vec<HubuumClassExpanded> = test::read_body_json(resp).await;
        assert_eq!(classes.len(), 2);
        assert_contains_all!(&created_classes[0..3], &classes);

        cleanup(&created_classes).await;
    }

    #[rstest]
    #[actix_web::test]
    async fn test_api_classes_get_by_id(#[future(awt)] test_context: TestContext) {
        let context = test_context;
        let created_classes = create_test_classes(&context, "api_classes_get_by_id").await;

        for class in &created_classes {
            let resp = get_request(
                &context.pool,
                &context.admin_token,
                &format!("{}/{}", CLASSES_ENDPOINT, class.id),
            )
            .await;
            let resp = assert_response_status(resp, StatusCode::OK).await;
            let returned_class: HubuumClassExpanded = test::read_body_json(resp).await;
            assert_eq!(class, &returned_class);
        }
        cleanup(&created_classes).await;
    }

    #[rstest]
    #[actix_web::test]
    async fn test_api_classes_get_failure(#[future(awt)] test_context: TestContext) {
        let context = test_context;

        // It'd be really nice if we could garantee that this id doesn't exist...
        for id in 999990..1000000 {
            let resp = get_request(
                &context.pool,
                &context.admin_token,
                &format!("{CLASSES_ENDPOINT}/{id}"),
            )
            .await;
            assert_response_status(resp, StatusCode::NOT_FOUND).await;
        }
    }

    #[rstest]
    #[actix_web::test]
    async fn test_api_classes_create(#[future(awt)] test_context: TestContext) {
        let context = test_context;

        let collection_fixture = context.collection_fixture("api_create_test_classes").await;

        let new_class = NewHubuumClass {
            name: "api_create_test_classes".to_string(),
            description: "api_create_test_classes".to_string(),
            collection_id: collection_fixture.collection.id,
            json_schema: Some(get_schema(SchemaType::Blog).clone()),
            validate_schema: Some(false),
        };

        let resp = post_request(
            &context.pool,
            &context.admin_token,
            CLASSES_ENDPOINT,
            &new_class,
        )
        .await;

        let resp = assert_response_status(resp, StatusCode::CREATED).await;
        let headers = resp.headers().clone();
        let created_class_from_create: HubuumClassExpanded = test::read_body_json(resp).await;
        let created_class_url = headers.get("Location").unwrap().to_str().unwrap();

        let resp = get_request(&context.pool, &context.admin_token, created_class_url).await;
        let resp = assert_response_status(resp, StatusCode::OK).await;
        let created_class: HubuumClassExpanded = test::read_body_json(resp).await;

        // Validate that the location is what we expect
        assert_eq!(
            created_class_url,
            &format!("{}/{}", CLASSES_ENDPOINT, created_class.id)
        );

        assert_eq!(created_class, created_class_from_create);
        collection_fixture.cleanup().await.unwrap();
    }

    #[rstest]
    #[case(serde_json::json!({"type": 7}))]
    #[case(serde_json::json!({"$ref": "https://example.com/schema.json"}))]
    #[case(serde_json::json!({"$ref": "file:///etc/passwd"}))]
    #[actix_web::test]
    async fn test_api_classes_rejects_unsafe_json_schemas(
        #[case] json_schema: serde_json::Value,
        #[future(awt)] test_context: TestContext,
    ) {
        let context = test_context;
        let collection = context.collection_fixture("reject_unsafe_schema").await;
        let new_class = NewHubuumClass {
            name: format!("unsafe_schema_{}", uuid::Uuid::new_v4().simple()),
            description: "invalid schema must not be persisted".to_string(),
            collection_id: collection.collection.id,
            json_schema: Some(json_schema),
            validate_schema: Some(true),
        };

        let response = post_request(
            &context.pool,
            &context.admin_token,
            CLASSES_ENDPOINT,
            &new_class,
        )
        .await;
        assert_response_status(response, StatusCode::BAD_REQUEST).await;
        collection.cleanup().await.unwrap();
    }

    #[rstest]
    #[actix_web::test]
    async fn test_api_classes_patch(#[future(awt)] test_context: TestContext) {
        use crate::models::UpdateHubuumClass;

        let context = test_context;

        let collection_fixture = context.collection_fixture("api_patch_test_classes").await;

        let new_class = NewHubuumClass {
            name: "api_patch_test_classes".to_string(),
            description: "api_patch_test_classes_desc".to_string(),
            collection_id: collection_fixture.collection.id,
            json_schema: Some(get_schema(SchemaType::Blog).clone()),
            validate_schema: None,
        };
        let created_class = new_class.save_without_events(&context.pool).await.unwrap();

        let update_class = UpdateHubuumClass {
            name: Some("api_patch_test_classes_2".to_string()),
            collection_id: None,
            json_schema: None,
            validate_schema: None,
            description: None,
        };

        let resp = patch_request(
            &context.pool,
            &context.admin_token,
            &format!("{}/{}", CLASSES_ENDPOINT, created_class.id),
            &update_class,
        )
        .await;

        let resp = assert_response_status(resp, StatusCode::OK).await;
        let updated_class_from_patch: HubuumClassExpanded = test::read_body_json(resp).await;
        let resp = get_request(
            &context.pool,
            &context.admin_token,
            &format!("{}/{}", CLASSES_ENDPOINT, created_class.id),
        )
        .await;
        let resp = assert_response_status(resp, StatusCode::OK).await;
        let updated_class_from_get: HubuumClassExpanded = test::read_body_json(resp).await;

        assert_eq!(updated_class_from_patch, updated_class_from_get);
        assert_ne!(created_class, updated_class_from_patch);

        assert_eq!(updated_class_from_patch.name, "api_patch_test_classes_2");
        assert_eq!(
            updated_class_from_patch.description,
            created_class.description
        );
        assert_eq!(
            updated_class_from_patch.collection.id,
            created_class.collection_id
        );
        assert_eq!(
            updated_class_from_patch.json_schema,
            created_class.json_schema
        );
        assert!(!updated_class_from_patch.validate_schema);
    }

    #[rstest]
    #[actix_web::test]
    async fn test_api_classes_patch_requires_target_collection_permission(
        #[future(awt)] test_context: TestContext,
    ) {
        use crate::models::UpdateHubuumClass;

        let context = test_context;
        let source = context
            .scope
            .collection_fixture("api_patch_class_move_source")
            .await;
        let target = context
            .scope
            .collection_fixture("api_patch_class_move_target")
            .await;
        let group = create_test_group(&context.pool).await;
        group
            .add_member_without_events(&context.pool, &context.normal_user)
            .await
            .unwrap();
        source
            .collection
            .grant_without_events(
                &context.pool,
                group.id,
                PermissionsList::new([Permissions::UpdateClass]),
            )
            .await
            .unwrap();

        let created_class = NewHubuumClass {
            name: "api_patch_class_move".to_string(),
            description: "api_patch_class_move".to_string(),
            collection_id: source.collection.id,
            json_schema: None,
            validate_schema: Some(false),
        }
        .save_without_events(&context.pool)
        .await
        .unwrap();

        let update_class = UpdateHubuumClass {
            name: None,
            collection_id: Some(target.collection.id),
            json_schema: None,
            validate_schema: None,
            description: None,
        };
        let url = format!("{}/{}", CLASSES_ENDPOINT, created_class.id);

        let resp = patch_request(&context.pool, &context.normal_token, &url, &update_class).await;
        let _ = assert_response_status(resp, StatusCode::FORBIDDEN).await;

        target
            .collection
            .grant_without_events(
                &context.pool,
                group.id,
                PermissionsList::new([Permissions::CreateClass]),
            )
            .await
            .unwrap();

        let resp = patch_request(&context.pool, &context.normal_token, &url, &update_class).await;
        let resp = assert_response_status(resp, StatusCode::OK).await;
        let updated_class: HubuumClassExpanded = test::read_body_json(resp).await;
        assert_eq!(updated_class.collection.id, target.collection.id);

        source.cleanup().await.unwrap();
        target.cleanup().await.unwrap();
        group.delete_without_events(&context.pool).await.unwrap();
    }

    #[rstest]
    #[actix_web::test]
    async fn test_api_classes_delete(#[future(awt)] test_context: TestContext) {
        let context = test_context;
        let created_classes = create_test_classes(&context, "api_classes_delete").await;

        for class in &created_classes {
            let resp = delete_request(
                &context.pool,
                &context.admin_token,
                &format!("{}/{}", CLASSES_ENDPOINT, class.id),
            )
            .await;
            assert_response_status(resp, StatusCode::NO_CONTENT).await;

            let resp = get_request(
                &context.pool,
                &context.admin_token,
                &format!("{}/{}", CLASSES_ENDPOINT, class.id),
            )
            .await;
            assert_response_status(resp, StatusCode::NOT_FOUND).await;
        }
    }

    #[rstest]
    #[case::sorted_id_default("id", &[0, 1, 2])]
    #[case::sorted_id_explicit_asc("id.asc", &[0, 1, 2])]
    #[case::sorted_id_descending("id.desc", &[5, 4, 3])]
    #[actix_web::test]
    async fn test_api_classes_sorted(
        #[case] sort_order: &str,
        #[case] expected_id_order: &[usize],
        #[future(awt)] test_context: TestContext,
    ) {
        let context = test_context;
        let created_classes = create_test_classes(
            &context,
            &format!("api_classes_sorted_{sort_order}_{expected_id_order:?}"),
        )
        .await;
        let collection_id = created_classes[0].collection_id;

        let sort_order = if sort_order.is_empty() {
            ""
        } else {
            &format!("&sort={sort_order}")
        };

        let resp = get_request(
            &context.pool,
            &context.admin_token,
            &format!("{CLASSES_ENDPOINT}?collections={collection_id}{sort_order}"),
        )
        .await;
        let resp = assert_response_status(resp, StatusCode::OK).await;
        let classes: Vec<HubuumClassExpanded> = test::read_body_json(resp).await;
        assert_eq!(classes.len(), created_classes.len());
        assert_eq!(classes[0].id, created_classes[expected_id_order[0]].id);
        assert_eq!(classes[1].id, created_classes[expected_id_order[1]].id);
        assert_eq!(classes[2].id, created_classes[expected_id_order[2]].id);

        cleanup(&created_classes).await;
    }

    #[rstest]
    #[case::limit_2(2)]
    #[case::limit_5(5)]
    #[case::limit_7(6)]
    #[actix_web::test]
    async fn test_api_classes_limit(
        #[case] limit: usize,
        #[future(awt)] test_context: TestContext,
    ) {
        let context = test_context;
        let created_classes =
            create_test_classes(&context, &format!("api_classes_limit_{limit}")).await;
        let collection_id = created_classes[0].collection_id;

        // Limit to 2 results
        let resp = get_request(
            &context.pool,
            &context.admin_token,
            &format!("{CLASSES_ENDPOINT}?collections={collection_id}&limit={limit}&sort=id"),
        )
        .await;
        let resp = assert_response_status(resp, StatusCode::OK).await;
        let classes: Vec<HubuumClassExpanded> = test::read_body_json(resp).await;
        assert_eq!(classes.len(), limit);

        cleanup(&created_classes).await;
    }

    // Covers docs/querying.md "Cursor pagination" (`X-Next-Cursor` is absent on the last page).
    #[rstest]
    #[actix_web::test]
    async fn docs_api_classes_cursor_pagination(#[future(awt)] test_context: TestContext) {
        let context = test_context;
        let created_classes = create_test_classes(&context, "api_classes_cursor").await;
        let collection_id = created_classes[0].collection_id;

        let resp = get_request(
            &context.pool,
            &context.admin_token,
            &format!("{CLASSES_ENDPOINT}?collections={collection_id}&limit=2&sort=id"),
        )
        .await;
        let resp = assert_response_status(resp, StatusCode::OK).await;
        let next_cursor = header_value(&resp, NEXT_CURSOR_HEADER);
        let total_count =
            header_value(&resp, TOTAL_COUNT_HEADER).and_then(|value| value.parse::<i64>().ok());
        let classes: Vec<HubuumClassExpanded> = test::read_body_json(resp).await;

        assert_eq!(classes.len(), 2);
        assert_eq!(classes[0].id, created_classes[0].id);
        assert_eq!(classes[1].id, created_classes[1].id);
        assert_eq!(total_count, Some(6));
        assert!(next_cursor.is_some());

        let resp = get_request(
            &context.pool,
            &context.admin_token,
            &format!(
                "{CLASSES_ENDPOINT}?collections={collection_id}&limit=2&sort=id&cursor={}",
                next_cursor.unwrap()
            ),
        )
        .await;
        let resp = assert_response_status(resp, StatusCode::OK).await;
        let second_cursor = header_value(&resp, NEXT_CURSOR_HEADER);
        let second_total_count =
            header_value(&resp, TOTAL_COUNT_HEADER).and_then(|value| value.parse::<i64>().ok());
        let classes: Vec<HubuumClassExpanded> = test::read_body_json(resp).await;

        assert_eq!(classes.len(), 2);
        assert_eq!(classes[0].id, created_classes[2].id);
        assert_eq!(classes[1].id, created_classes[3].id);
        assert_eq!(second_total_count, Some(6));
        assert!(second_cursor.is_some());

        let resp = get_request(
            &context.pool,
            &context.admin_token,
            &format!(
                "{CLASSES_ENDPOINT}?collections={collection_id}&limit=2&sort=id&cursor={}",
                second_cursor.unwrap()
            ),
        )
        .await;
        let resp = assert_response_status(resp, StatusCode::OK).await;
        let final_cursor = header_value(&resp, NEXT_CURSOR_HEADER);
        let final_total_count =
            header_value(&resp, TOTAL_COUNT_HEADER).and_then(|value| value.parse::<i64>().ok());
        let classes: Vec<HubuumClassExpanded> = test::read_body_json(resp).await;

        assert_eq!(classes.len(), 2);
        assert_eq!(classes[0].id, created_classes[4].id);
        assert_eq!(classes[1].id, created_classes[5].id);
        assert_eq!(final_total_count, Some(6));
        assert!(final_cursor.is_none());

        cleanup(&created_classes).await;
    }

    #[rstest]
    #[actix_web::test]
    async fn test_api_create_records_actor(#[future(awt)] test_context: TestContext) {
        use crate::db::prelude::*;
        use crate::db::with_connection;

        let context = test_context;
        let collection_fixture = context.collection_fixture("actor_history").await;

        let new_class = NewHubuumClass {
            name: format!("{}_class", collection_fixture.collection.name),
            description: "d".to_string(),
            collection_id: collection_fixture.collection.id,
            json_schema: None,
            validate_schema: Some(false),
        };

        let resp = post_request(
            &context.pool,
            &context.admin_token,
            CLASSES_ENDPOINT,
            &new_class,
        )
        .await;
        let resp = assert_response_status(resp, StatusCode::CREATED).await;
        let created: HubuumClassExpanded = test::read_body_json(resp).await;

        // The user behind admin_token, resolved straight from the tokens table.
        let token_hash = crate::models::token::Token::storage_hash_from_raw(&context.admin_token);
        let expected_actor: i32 = with_connection(&context.pool, async |conn| {
            use crate::schema::tokens::dsl as t;
            t::tokens
                .filter(t::token.eq(&token_hash))
                .select(t::principal_id)
                .first::<i32>(conn)
                .await
        })
        .await
        .unwrap();

        let actor: Option<i32> = with_connection(&context.pool, async |conn| {
            use crate::schema::hubuumclass_history::dsl as h;
            h::hubuumclass_history
                .filter(h::id.eq(created.id))
                .order(h::history_id.desc())
                .select(h::actor_id)
                .first::<Option<i32>>(conn)
                .await
        })
        .await
        .unwrap();

        assert_eq!(
            actor,
            Some(expected_actor),
            "history must attribute the create to the requestor"
        );
        collection_fixture.cleanup().await.unwrap();
    }

    #[rstest]
    #[actix_web::test]
    async fn test_api_class_history_list_and_as_of(#[future(awt)] test_context: TestContext) {
        use crate::models::UpdateHubuumClass;
        use crate::traits::{CanSave, CanUpdate};

        let context = test_context;
        let collection_fixture = context.collection_fixture("class_history_api").await;
        let event_context = hubuum_events_core::EventContext::system();

        // Create then update so there are two versions.
        let created = NewHubuumClass {
            name: "class_history_api".to_string(),
            description: "v1".to_string(),
            collection_id: collection_fixture.collection.id,
            json_schema: None,
            validate_schema: Some(false),
        }
        .save(&context.pool, &event_context)
        .await
        .unwrap();
        UpdateHubuumClass {
            name: None,
            collection_id: None,
            json_schema: None,
            validate_schema: None,
            description: Some("v2".to_string()),
        }
        .update(&context.pool, created.id, &event_context)
        .await
        .unwrap();

        // List history newest-first.
        let resp = get_request(
            &context.pool,
            &context.admin_token,
            &format!("{}/{}/history", CLASSES_ENDPOINT, created.id),
        )
        .await;
        let resp = assert_response_status(resp, StatusCode::OK).await;
        let body: Vec<serde_json::Value> = test::read_body_json(resp).await;
        assert_eq!(body.len(), 2, "expected two versions");
        assert_eq!(body[0]["op"], "U");
        assert_eq!(body[0]["description"], "v2");
        assert_eq!(body[1]["op"], "I");
        assert!(
            body[0].get("actor_username").is_some(),
            "actor_username key present"
        );

        // as-of just after the insert (before the update) -> v1.
        let v1_from = body[1]["valid_from"].as_str().unwrap().to_string();
        let resp = get_request(
            &context.pool,
            &context.admin_token,
            &format!(
                "{}/{}/history/as-of?at={}",
                CLASSES_ENDPOINT, created.id, v1_from
            ),
        )
        .await;
        let resp = assert_response_status(resp, StatusCode::OK).await;
        let snap: serde_json::Value = test::read_body_json(resp).await;
        assert_eq!(snap["description"], "v1");

        collection_fixture.cleanup().await.unwrap();
    }

    #[rstest]
    #[actix_web::test]
    async fn test_api_class_history_404_for_missing(#[future(awt)] test_context: TestContext) {
        let context = test_context;
        let resp = get_request(
            &context.pool,
            &context.admin_token,
            &format!("{}/2147483647/history", CLASSES_ENDPOINT),
        )
        .await;
        assert_response_status(resp, StatusCode::NOT_FOUND).await;
    }

    #[rstest]
    #[actix_web::test]
    async fn test_admin_can_read_deleted_class_history(#[future(awt)] test_context: TestContext) {
        use crate::traits::{CanDelete, CanSave};

        let context = test_context;
        let collection_fixture = context.collection_fixture("deleted_class_history").await;
        let event_context = hubuum_events_core::EventContext::system();
        let class = NewHubuumClass {
            name: "deleted_class_history".to_string(),
            description: "v1".to_string(),
            collection_id: collection_fixture.collection.id,
            json_schema: None,
            validate_schema: Some(false),
        }
        .save(&context.pool, &event_context)
        .await
        .unwrap();
        let class_id = class.id;
        class.delete(&context.pool, &event_context).await.unwrap();

        let normal_resp = get_request(
            &context.pool,
            &context.normal_token,
            &format!("{}/{}/history", CLASSES_ENDPOINT, class_id),
        )
        .await;
        assert_response_status(normal_resp, StatusCode::NOT_FOUND).await;

        let admin_resp = get_request(
            &context.pool,
            &context.admin_token,
            &format!("{}/{}/history", CLASSES_ENDPOINT, class_id),
        )
        .await;
        let admin_resp = assert_response_status(admin_resp, StatusCode::OK).await;
        let body: Vec<serde_json::Value> = test::read_body_json(admin_resp).await;

        assert_eq!(body.len(), 2);
        assert_eq!(body[0]["op"], "D");
        assert_eq!(body[1]["op"], "I");

        collection_fixture.cleanup().await.unwrap();
    }

    #[rstest]
    #[actix_web::test]
    async fn test_api_class_history_cursor_pagination(#[future(awt)] test_context: TestContext) {
        use crate::models::UpdateHubuumClass;
        use crate::traits::{CanSave, CanUpdate};

        let context = test_context;
        let collection_fixture = context.collection_fixture("class_history_cursor").await;
        let event_context = hubuum_events_core::EventContext::system();

        // Create then update TWICE to have three history rows (I, U, U).
        let created = NewHubuumClass {
            name: "class_history_cursor".to_string(),
            description: "v1".to_string(),
            collection_id: collection_fixture.collection.id,
            json_schema: None,
            validate_schema: Some(false),
        }
        .save(&context.pool, &event_context)
        .await
        .unwrap();

        UpdateHubuumClass {
            name: None,
            collection_id: None,
            json_schema: None,
            validate_schema: None,
            description: Some("v2".to_string()),
        }
        .update(&context.pool, created.id, &event_context)
        .await
        .unwrap();

        UpdateHubuumClass {
            name: None,
            collection_id: None,
            json_schema: None,
            validate_schema: None,
            description: Some("v3".to_string()),
        }
        .update(&context.pool, created.id, &event_context)
        .await
        .unwrap();

        // Page 1: limit=2, should get the two newest versions (v3, v2), newest-first.
        let resp = get_request(
            &context.pool,
            &context.admin_token,
            &format!("{}/{}/history?limit=2", CLASSES_ENDPOINT, created.id),
        )
        .await;
        let resp = assert_response_status(resp, StatusCode::OK).await;

        let total_count =
            header_value(&resp, TOTAL_COUNT_HEADER).and_then(|value| value.parse::<i64>().ok());
        assert_eq!(total_count, Some(3), "total version count should be 3");

        let next_cursor = header_value(&resp, NEXT_CURSOR_HEADER);
        assert!(next_cursor.is_some(), "page 1 should have a next cursor");

        let page1: Vec<serde_json::Value> = test::read_body_json(resp).await;
        assert_eq!(page1.len(), 2, "page 1 should have 2 items");
        assert_eq!(page1[0]["description"], "v3", "first item should be v3");
        assert_eq!(page1[1]["description"], "v2", "second item should be v2");

        // Page 2: use the cursor to get the third (oldest) version (v1).
        let cursor = next_cursor.unwrap();
        let resp = get_request(
            &context.pool,
            &context.admin_token,
            &format!(
                "{}/{}/history?limit=2&cursor={}",
                CLASSES_ENDPOINT, created.id, cursor
            ),
        )
        .await;
        let resp = assert_response_status(resp, StatusCode::OK).await;

        let next_cursor_page2 = header_value(&resp, NEXT_CURSOR_HEADER);
        assert!(
            next_cursor_page2.is_none(),
            "page 2 (last page) should not have a next cursor"
        );

        let page2: Vec<serde_json::Value> = test::read_body_json(resp).await;
        assert_eq!(page2.len(), 1, "page 2 should have 1 item");
        assert_eq!(page2[0]["description"], "v1", "third item should be v1");
        assert_eq!(page2[0]["op"], "I", "oldest version should be an insert");

        // Verify no overlap: the history_id or valid_from must differ.
        let page1_history_ids: Vec<i64> = page1
            .iter()
            .map(|v| v["history_id"].as_i64().unwrap())
            .collect();
        let page2_history_id = page2[0]["history_id"].as_i64().unwrap();
        assert!(
            !page1_history_ids.contains(&page2_history_id),
            "page 2 history_id should not appear in page 1"
        );

        collection_fixture.cleanup().await.unwrap();
    }

    #[rstest]
    #[actix_web::test]
    async fn class_update_validates_the_schema_locked_for_the_write(
        #[future(awt)] test_context: TestContext,
    ) {
        let collection = test_context
            .collection_fixture("class schema update lock")
            .await;
        let class = NewHubuumClass {
            name: test_context.scoped_name("class schema update lock"),
            collection_id: collection.collection.id,
            json_schema: Some(serde_json::json!({"type": "object"})),
            validate_schema: Some(false),
            description: String::new(),
        }
        .save(&test_context.pool, &EventContext::system())
        .await
        .unwrap();
        let target = ClassSelector::by_id(HubuumClassID::new(class.id).unwrap())
            .resolve_class_target(&test_context.pool)
            .await
            .unwrap();
        let update_pool = test_context.pool.clone();
        let class_id = class.id;

        let update_task = with_transaction(&test_context.pool, async |conn| {
            use crate::schema::hubuumclass::dsl::{hubuumclass, id, json_schema};

            diesel::update(hubuumclass.filter(id.eq(class_id)))
                .set(json_schema.eq(Some(serde_json::json!({
                    "$ref": "https://example.com/schema.json"
                }))))
                .execute(conn)
                .await?;

            let task = tokio::spawn(async move {
                UpdateHubuumClass {
                    name: None,
                    collection_id: None,
                    json_schema: None,
                    validate_schema: Some(true),
                    description: None,
                }
                .update_resolved_class(&update_pool, &target, &EventContext::system())
                .await
            });
            tokio::time::sleep(Duration::from_millis(100)).await;
            Ok::<_, diesel::result::Error>(task)
        })
        .await
        .unwrap();

        let error = update_task.await.unwrap().unwrap_err();
        assert!(matches!(error, ApiError::BadRequest(_)));
        let current = HubuumClassID::new(class.id)
            .unwrap()
            .instance(&test_context.pool)
            .await
            .unwrap();
        assert!(!current.validate_schema);

        collection.cleanup().await.unwrap();
    }
}
