#!/usr/bin/env python3
"""Generate documentation inventories from Cargo metadata and TaskKind's enum."""
import argparse
import json
from pathlib import Path
import re
import subprocess

ROOT = Path(__file__).resolve().parent.parent


def inventory():
    metadata = json.loads(subprocess.check_output(
        ["cargo", "metadata", "--locked", "--format-version", "1", "--no-deps"], cwd=ROOT
    ))
    members = set(metadata["workspace_members"])
    packages = [p for p in metadata["packages"] if p["id"] in members]
    sdk = [{"name": p["name"], "version": p["version"], "rust_version": p["rust_version"]}
           for p in packages if p["metadata"].get("hubuum", {}).get("release-train") == "storage-sdk"]
    source = (ROOT / "src/models/task.rs").read_text()
    match = re.search(r"pub enum TaskKind\s*\{([^}]+)\}", source)
    if not match:
        raise ValueError("TaskKind enum was not found")
    variants = [v.strip() for v in match.group(1).split(",") if v.strip()]
    if any(not re.fullmatch(r"[A-Z][a-zA-Z]+", v) for v in variants):
        raise ValueError("TaskKind representation changed; update the inventory generator")
    tasks = [re.sub(r"(?<!^)(?=[A-Z])", "_", v).lower() for v in variants]
    binaries = sorted(t["name"] for p in packages for t in p["targets"] if "bin" in t["kind"])
    return {"storage_sdk": sorted(sdk, key=lambda p: p["name"]), "task_kinds": tasks, "binaries": binaries}


def documents(data):
    lines = ["# Project inventory", "", "Generated by `python3 scripts/generate-project-inventory.py`; do not edit by hand.",
             "", "## Storage SDK", "", "| Package | Version | Minimum Rust |", "| --- | --- | --- |"]
    lines += [f"| `{p['name']}` | {p['version']} | {p['rust_version']} |" for p in data["storage_sdk"]]
    lines += ["", "## Task kinds", ""] + [f"- `{kind}`" for kind in data["task_kinds"]]
    lines += ["", "Every task kind is covered by the worker's exhaustive dispatch and the inventory contract test.",
              "", "## Workspace executables", ""] + [f"- `{name}`" for name in data["binaries"]]
    return {"project_inventory.json": json.dumps(data, indent=2) + "\n", "project_inventory.md": "\n".join(lines) + "\n"}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    for name, content in documents(inventory()).items():
        path = ROOT / "docs/generated" / name
        if args.check:
            if not path.exists() or path.read_text() != content:
                parser.exit(1, f"{path.relative_to(ROOT)} is stale; run this script without --check\n")
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)


if __name__ == "__main__":
    main()
