//! SQL → Cedar policy export.
//!
//! Walks the `permissions` table and emits one Cedar `permit` clause per
//! `(group_id, namespace_id, resource_kind)` bucket. The output is a
//! complete Cedar policy bundle that, when uploaded to a Treetop server
//! configured with `docs/treetop/schema.cedarschema`, grants exactly the
//! permissions the SQL table currently records.
//!
//! This is a one-shot tool: Hubuum does not push policies at runtime;
//! the operator uploads the file via Treetop's own tooling. See
//! `docs/treetop/README.md` for the bootstrap workflow.

use std::io::Write;

use diesel::prelude::*;

use crate::db::{DbPool, with_connection};
use crate::errors::ApiError;
use crate::models::{Group, Namespace, Permission};

/// Helper macro to convert io::Error to ApiError for writeln! calls
macro_rules! w {
    ($writer:expr) => {
        writeln!($writer).map_err(|e| ApiError::InternalServerError(format!("failed to write output: {e}")))
    };
    ($writer:expr, $($arg:tt)*) => {
        writeln!($writer, $($arg)*).map_err(|e| ApiError::InternalServerError(format!("failed to write output: {e}")))
    };
}

/// Emit the Cedar bundle to `writer`.
pub async fn export_cedar_to<W: Write>(pool: &DbPool, writer: &mut W) -> Result<(), ApiError> {
    use crate::schema::{groups, namespaces, permissions as perms_schema};

    let rows: Vec<(Permission, Group, Namespace)> = with_connection(pool, |conn| {
        perms_schema::table
            .inner_join(groups::table.on(perms_schema::group_id.eq(groups::id)))
            .inner_join(namespaces::table.on(perms_schema::namespace_id.eq(namespaces::id)))
            .order_by((
                perms_schema::namespace_id.asc(),
                perms_schema::group_id.asc(),
            ))
            .load::<(Permission, Group, Namespace)>(conn)
    })?;

    w!(
        writer,
        "// Generated by `hubuum-admin export-permissions --as cedar`"
    )?;
    w!(
        writer,
        "// Each permit clause covers one (group, namespace, resource_kind) bucket."
    )?;
    w!(
        writer,
        "// Group IDs and Namespace IDs are numeric; names appear in comments only."
    )?;
    w!(writer, "//")?;
    w!(writer, "// Source: SQL permissions table at export time.")?;
    w!(writer, "//")?;
    w!(
        writer,
        "// Note: relation permits use OR-on-endpoints — a user with this permission"
    )?;
    w!(
        writer,
        "// on EITHER endpoint namespace can act on the relation. The Local SQL"
    )?;
    w!(
        writer,
        "// backend uses AND (permission required on both endpoints). Operators"
    )?;
    w!(
        writer,
        "// who need AND semantics in Treetop should add forbid clauses or rewrite"
    )?;
    w!(writer, "// the relation permits manually.")?;
    w!(writer)?;

    for (perm, group, namespace) in &rows {
        emit_collection_actions(writer, perm, group, namespace)?;
        emit_class_actions(writer, perm, group, namespace)?;
        emit_object_actions(writer, perm, group, namespace)?;
        emit_class_relation_actions(writer, perm, group, namespace)?;
        emit_object_relation_actions(writer, perm, group, namespace)?;
        emit_template_actions(writer, perm, group, namespace)?;
    }

    Ok(())
}

fn emit_block<W: Write>(
    writer: &mut W,
    perm: &Permission,
    group: &Group,
    namespace: &Namespace,
    resource_type: &str,
    actions: &[&str],
    extra_when: Option<&str>,
) -> Result<(), ApiError> {
    if actions.is_empty() {
        return Ok(());
    }

    w!(
        writer,
        "// permission row id={} group={} ({}) namespace={} ({})",
        perm.id,
        group.id,
        group.groupname,
        namespace.id,
        namespace.name
    )?;
    w!(writer, "permit(")?;
    w!(writer, "    principal in Group::\"{}\",", group.id)?;
    w!(
        writer,
        "    action in [{}],",
        actions
            .iter()
            .map(|a| format!("Action::\"{a}\""))
            .collect::<Vec<_>>()
            .join(", ")
    )?;
    w!(writer, "    resource")?;
    w!(writer, ") when {{")?;
    w!(
        writer,
        "    resource is {} && resource.namespace_id == {}{}",
        resource_type,
        namespace.id,
        extra_when.unwrap_or("")
    )?;
    w!(writer, "}};")?;
    w!(writer)?;
    Ok(())
}

fn emit_collection_actions<W: Write>(
    writer: &mut W,
    perm: &Permission,
    group: &Group,
    namespace: &Namespace,
) -> Result<(), ApiError> {
    let mut actions = Vec::new();
    if perm.has_read_namespace {
        actions.push("ReadCollection");
    }
    if perm.has_update_namespace {
        actions.push("UpdateCollection");
    }
    if perm.has_delete_namespace {
        actions.push("DeleteCollection");
    }
    if perm.has_delegate_namespace {
        actions.push("DelegateCollection");
    }
    if actions.is_empty() {
        return Ok(());
    }

    // Collection-level permits scope the resource to the Namespace
    // entity itself, not via .namespace_id (the namespace IS the
    // resource). Use a different shape than the helper above.
    w!(
        writer,
        "// permission row id={} group={} ({}) namespace={} ({})",
        perm.id,
        group.id,
        group.groupname,
        namespace.id,
        namespace.name
    )?;
    w!(writer, "permit(")?;
    w!(writer, "    principal in Group::\"{}\",", group.id)?;
    w!(
        writer,
        "    action in [{}],",
        actions
            .iter()
            .map(|a| format!("Action::\"{a}\""))
            .collect::<Vec<_>>()
            .join(", ")
    )?;
    w!(writer, "    resource")?;
    w!(writer, ") when {{")?;
    w!(
        writer,
        "    resource is HubuumNamespace && resource == HubuumNamespace::\"{}\"",
        namespace.id
    )?;
    w!(writer, "}};")?;
    w!(writer)?;
    Ok(())
}

fn emit_class_actions<W: Write>(
    writer: &mut W,
    perm: &Permission,
    group: &Group,
    namespace: &Namespace,
) -> Result<(), ApiError> {
    let mut actions = Vec::new();
    if perm.has_read_class {
        actions.push("ReadClass");
    }
    if perm.has_update_class {
        actions.push("UpdateClass");
    }
    if perm.has_delete_class {
        actions.push("DeleteClass");
    }
    if perm.has_create_class {
        actions.push("CreateClass");
    }
    emit_block(
        writer,
        perm,
        group,
        namespace,
        "HubuumClass",
        &actions,
        None,
    )
}

fn emit_object_actions<W: Write>(
    writer: &mut W,
    perm: &Permission,
    group: &Group,
    namespace: &Namespace,
) -> Result<(), ApiError> {
    let mut actions = Vec::new();
    if perm.has_read_object {
        actions.push("ReadObject");
    }
    if perm.has_update_object {
        actions.push("UpdateObject");
    }
    if perm.has_delete_object {
        actions.push("DeleteObject");
    }
    if perm.has_create_object {
        actions.push("CreateObject");
    }
    emit_block(
        writer,
        perm,
        group,
        namespace,
        "HubuumObject",
        &actions,
        None,
    )
}

fn emit_class_relation_actions<W: Write>(
    writer: &mut W,
    perm: &Permission,
    group: &Group,
    namespace: &Namespace,
) -> Result<(), ApiError> {
    let mut actions = Vec::new();
    if perm.has_read_class_relation {
        actions.push("ReadClassRelation");
    }
    if perm.has_update_class_relation {
        actions.push("UpdateClassRelation");
    }
    if perm.has_delete_class_relation {
        actions.push("DeleteClassRelation");
    }
    if perm.has_create_class_relation {
        actions.push("CreateClassRelation");
    }
    // For class relations, the resource attribute namespace_id won't
    // necessarily equal the namespace this row authorizes — relations
    // span two namespaces. The Local backend's AND-check handles this
    // via from_namespace_id/to_namespace_id; the Cedar policy mirrors
    // that by checking "the row's namespace appears as either endpoint."
    emit_block(
        writer,
        perm,
        group,
        namespace,
        "HubuumClassRelation",
        &actions,
        Some(&format!(
            " && (resource.from_namespace_id == {nid} || resource.to_namespace_id == {nid})",
            nid = namespace.id,
        )),
    )?;
    Ok(())
}

fn emit_object_relation_actions<W: Write>(
    writer: &mut W,
    perm: &Permission,
    group: &Group,
    namespace: &Namespace,
) -> Result<(), ApiError> {
    let mut actions = Vec::new();
    if perm.has_read_object_relation {
        actions.push("ReadObjectRelation");
    }
    if perm.has_update_object_relation {
        actions.push("UpdateObjectRelation");
    }
    if perm.has_delete_object_relation {
        actions.push("DeleteObjectRelation");
    }
    if perm.has_create_object_relation {
        actions.push("CreateObjectRelation");
    }
    emit_block(
        writer,
        perm,
        group,
        namespace,
        "HubuumObjectRelation",
        &actions,
        Some(&format!(
            " && (resource.from_namespace_id == {nid} || resource.to_namespace_id == {nid})",
            nid = namespace.id,
        )),
    )?;
    Ok(())
}

fn emit_template_actions<W: Write>(
    writer: &mut W,
    perm: &Permission,
    group: &Group,
    namespace: &Namespace,
) -> Result<(), ApiError> {
    let mut actions = Vec::new();
    if perm.has_read_template {
        actions.push("ReadTemplate");
    }
    if perm.has_create_template {
        actions.push("CreateTemplate");
    }
    if perm.has_update_template {
        actions.push("UpdateTemplate");
    }
    if perm.has_delete_template {
        actions.push("DeleteTemplate");
    }
    emit_block(
        writer,
        perm,
        group,
        namespace,
        "HubuumTemplate",
        &actions,
        None,
    )
}
