//! SQL → Cedar policy export.
//!
//! Walks the `permissions` table and emits one Cedar `permit` clause per
//! `(group_id, collection_id, resource_kind)` bucket. The output is a
//! complete Cedar policy bundle that, when uploaded to a Treetop server
//! configured with `docs/treetop/schema.cedarschema`, grants exactly the
//! permissions the SQL table currently records.
//!
//! This is a one-shot tool: Hubuum does not push policies at runtime;
//! the operator uploads the file via Treetop's own tooling. See
//! `docs/treetop/README.md` for the bootstrap workflow.

use std::io::Write;

use crate::db::prelude::*;

use crate::db::{DbPool, with_connection};
use crate::errors::ApiError;
use crate::models::{Collection, Group, Permission};

/// Helper macro to convert io::Error to ApiError for writeln! calls
macro_rules! w {
    ($writer:expr) => {
        writeln!($writer).map_err(|e| ApiError::InternalServerError(format!("failed to write output: {e}")))
    };
    ($writer:expr, $($arg:tt)*) => {
        writeln!($writer, $($arg)*).map_err(|e| ApiError::InternalServerError(format!("failed to write output: {e}")))
    };
}

/// Emit the Cedar bundle to `writer`.
pub async fn export_cedar_to<W: Write>(pool: &DbPool, writer: &mut W) -> Result<(), ApiError> {
    use crate::schema::{collections, groups, permissions as perms_schema};

    let rows: Vec<(Permission, Group, Collection)> = with_connection(pool, async |conn| {
        perms_schema::table
            .inner_join(groups::table.on(perms_schema::group_id.eq(groups::id)))
            .inner_join(collections::table.on(perms_schema::collection_id.eq(collections::id)))
            .order_by((
                perms_schema::collection_id.asc(),
                perms_schema::group_id.asc(),
            ))
            .load::<(Permission, Group, Collection)>(conn)
            .await
    })
    .await?;

    w!(
        writer,
        "// Generated by `hubuum-admin export-permissions --as cedar`"
    )?;
    w!(
        writer,
        "// Each permit clause covers one (group, collection, resource_kind) bucket."
    )?;
    w!(
        writer,
        "// Group IDs and Collection IDs are numeric; names appear in comments only."
    )?;
    w!(writer, "//")?;
    w!(writer, "// Source: SQL permissions table at export time.")?;
    w!(writer, "//")?;
    w!(
        writer,
        "// Note: relation permits use OR-on-endpoints — a user with this permission"
    )?;
    w!(
        writer,
        "// on EITHER endpoint collection can act on the relation. The Local SQL"
    )?;
    w!(
        writer,
        "// backend uses AND (permission required on both endpoints). Operators"
    )?;
    w!(
        writer,
        "// who need AND semantics in Treetop should add forbid clauses or rewrite"
    )?;
    w!(writer, "// the relation permits manually.")?;
    w!(writer)?;

    for (perm, group, collection) in &rows {
        emit_collection_actions(writer, perm, group, collection)?;
        emit_class_actions(writer, perm, group, collection)?;
        emit_object_actions(writer, perm, group, collection)?;
        emit_class_relation_actions(writer, perm, group, collection)?;
        emit_object_relation_actions(writer, perm, group, collection)?;
        emit_template_actions(writer, perm, group, collection)?;
    }

    Ok(())
}

/// Emit one `permit` clause. The caller passes the entire `when`
/// predicate as a fully-formed Cedar boolean expression so the emitter
/// doesn't have to know which resources have a `collection_id` attribute.
/// Relations don't carry a `collection_id` (only `from_collection_id` and
/// `to_collection_id`), so a previous version that always prepended
/// `resource.collection_id == N` produced policies that always evaluated
/// false on a real Cedar engine.
fn emit_block<W: Write>(
    writer: &mut W,
    perm: &Permission,
    group: &Group,
    collection: &Collection,
    actions: &[&str],
    when_predicate: &str,
) -> Result<(), ApiError> {
    if actions.is_empty() {
        return Ok(());
    }

    w!(
        writer,
        "// permission row id={} group={} ({}) collection={} ({})",
        perm.id,
        group.id,
        group.groupname,
        collection.id,
        collection.name
    )?;
    w!(writer, "permit(")?;
    w!(writer, "    principal in Group::\"{}\",", group.id)?;
    w!(
        writer,
        "    action in [{}],",
        actions
            .iter()
            .map(|a| format!("Action::\"{a}\""))
            .collect::<Vec<_>>()
            .join(", ")
    )?;
    w!(writer, "    resource")?;
    w!(writer, ") when {{")?;
    w!(writer, "    {}", when_predicate)?;
    w!(writer, "}};")?;
    w!(writer)?;
    Ok(())
}

/// Predicate matching child resources scoped to a collection via the
/// `collection_id` attribute. Used for HubuumClass / HubuumObject /
/// HubuumTemplate.
fn child_resource_predicate(resource_type: &str, collection_id: i32) -> String {
    format!("resource is {resource_type} && resource.collection_id == {collection_id}")
}

/// Predicate matching a relation whose either endpoint sits in the given
/// collection. Relations don't have a `collection_id` attribute — only
/// `from_collection_id` / `to_collection_id` — so the predicate must NOT
/// reference `resource.collection_id`.
fn relation_resource_predicate(resource_type: &str, collection_id: i32) -> String {
    format!(
        "resource is {resource_type} && \
         (resource.from_collection_id == {collection_id} || \
          resource.to_collection_id == {collection_id})"
    )
}

fn emit_collection_actions<W: Write>(
    writer: &mut W,
    perm: &Permission,
    group: &Group,
    collection: &Collection,
) -> Result<(), ApiError> {
    let mut actions = Vec::new();
    if perm.has_read_collection {
        actions.push("ReadCollection");
    }
    if perm.has_update_collection {
        actions.push("UpdateCollection");
    }
    if perm.has_delete_collection {
        actions.push("DeleteCollection");
    }
    if perm.has_delegate_collection {
        actions.push("DelegateCollection");
    }
    if perm.has_read_remote_target {
        actions.push("ReadRemoteTarget");
    }
    if perm.has_create_remote_target {
        actions.push("CreateRemoteTarget");
    }
    if perm.has_update_remote_target {
        actions.push("UpdateRemoteTarget");
    }
    if perm.has_delete_remote_target {
        actions.push("DeleteRemoteTarget");
    }
    if perm.has_execute_remote_target {
        actions.push("ExecuteRemoteTarget");
    }
    if perm.has_read_audit {
        actions.push("ReadAudit");
    }
    if perm.has_manage_event_subscription {
        actions.push("ManageEventSubscription");
    }
    if actions.is_empty() {
        return Ok(());
    }

    // Collection-level permits scope the resource to the Collection
    // entity itself, not via .collection_id (the collection IS the
    // resource). Use a different shape than the helper above.
    w!(
        writer,
        "// permission row id={} group={} ({}) collection={} ({})",
        perm.id,
        group.id,
        group.groupname,
        collection.id,
        collection.name
    )?;
    w!(writer, "permit(")?;
    w!(writer, "    principal in Group::\"{}\",", group.id)?;
    w!(
        writer,
        "    action in [{}],",
        actions
            .iter()
            .map(|a| format!("Action::\"{a}\""))
            .collect::<Vec<_>>()
            .join(", ")
    )?;
    w!(writer, "    resource")?;
    w!(writer, ") when {{")?;
    w!(
        writer,
        "    resource is HubuumCollection && resource == HubuumCollection::\"{}\"",
        collection.id
    )?;
    w!(writer, "}};")?;
    w!(writer)?;
    Ok(())
}

fn emit_class_actions<W: Write>(
    writer: &mut W,
    perm: &Permission,
    group: &Group,
    collection: &Collection,
) -> Result<(), ApiError> {
    let mut actions = Vec::new();
    if perm.has_read_class {
        actions.push("ReadClass");
    }
    if perm.has_update_class {
        actions.push("UpdateClass");
    }
    if perm.has_delete_class {
        actions.push("DeleteClass");
    }
    if perm.has_create_class {
        actions.push("CreateClass");
    }
    emit_block(
        writer,
        perm,
        group,
        collection,
        &actions,
        &child_resource_predicate("HubuumClass", collection.id),
    )
}

fn emit_object_actions<W: Write>(
    writer: &mut W,
    perm: &Permission,
    group: &Group,
    collection: &Collection,
) -> Result<(), ApiError> {
    let mut actions = Vec::new();
    if perm.has_read_object {
        actions.push("ReadObject");
    }
    if perm.has_update_object {
        actions.push("UpdateObject");
    }
    if perm.has_delete_object {
        actions.push("DeleteObject");
    }
    if perm.has_create_object {
        actions.push("CreateObject");
    }
    emit_block(
        writer,
        perm,
        group,
        collection,
        &actions,
        &child_resource_predicate("HubuumObject", collection.id),
    )
}

fn emit_class_relation_actions<W: Write>(
    writer: &mut W,
    perm: &Permission,
    group: &Group,
    collection: &Collection,
) -> Result<(), ApiError> {
    let mut actions = Vec::new();
    if perm.has_read_class_relation {
        actions.push("ReadClassRelation");
    }
    if perm.has_update_class_relation {
        actions.push("UpdateClassRelation");
    }
    if perm.has_delete_class_relation {
        actions.push("DeleteClassRelation");
    }
    if perm.has_create_class_relation {
        actions.push("CreateClassRelation");
    }
    // Relations have NO `collection_id` attribute in the Cedar schema —
    // they expose `from_collection_id` and `to_collection_id` only. The
    // predicate matches the row's collection as either endpoint (OR).
    // The Local backend's AND-on-both-endpoints semantics is the
    // documented divergence (see header comment in this file).
    emit_block(
        writer,
        perm,
        group,
        collection,
        &actions,
        &relation_resource_predicate("HubuumClassRelation", collection.id),
    )?;
    Ok(())
}

fn emit_object_relation_actions<W: Write>(
    writer: &mut W,
    perm: &Permission,
    group: &Group,
    collection: &Collection,
) -> Result<(), ApiError> {
    let mut actions = Vec::new();
    if perm.has_read_object_relation {
        actions.push("ReadObjectRelation");
    }
    if perm.has_update_object_relation {
        actions.push("UpdateObjectRelation");
    }
    if perm.has_delete_object_relation {
        actions.push("DeleteObjectRelation");
    }
    if perm.has_create_object_relation {
        actions.push("CreateObjectRelation");
    }
    emit_block(
        writer,
        perm,
        group,
        collection,
        &actions,
        &relation_resource_predicate("HubuumObjectRelation", collection.id),
    )?;
    Ok(())
}

fn emit_template_actions<W: Write>(
    writer: &mut W,
    perm: &Permission,
    group: &Group,
    collection: &Collection,
) -> Result<(), ApiError> {
    let mut actions = Vec::new();
    if perm.has_read_template {
        actions.push("ReadTemplate");
    }
    if perm.has_create_template {
        actions.push("CreateTemplate");
    }
    if perm.has_update_template {
        actions.push("UpdateTemplate");
    }
    if perm.has_delete_template {
        actions.push("DeleteTemplate");
    }
    emit_block(
        writer,
        perm,
        group,
        collection,
        &actions,
        &child_resource_predicate("HubuumTemplate", collection.id),
    )
}
