//! PostgreSQL implementations of backend-neutral storage operations.

pub mod authentication;
pub mod authorization;
pub mod backup;
pub mod bootstrap;
pub mod catalog;
pub mod class;
pub mod collection;
pub mod computed_materialization;
pub mod event_audit;
pub mod event_delivery;
pub mod event_fanout;
pub mod event_observability;
pub mod event_record;
pub mod event_retention;
mod event_rows;
pub mod event_subscription;
pub mod group;
pub mod history;
pub mod identity_credentials;
pub mod identity_principals;
pub mod identity_scope;
pub mod inventory;
pub mod maintenance;
pub mod meta;
pub mod metrics;
pub mod object;
pub mod principal;
pub mod probe;
pub mod relation;
pub mod remote_target;
pub mod token_retention;
pub mod unified_search;
pub mod user;
