use actix_web::web;

use crate::api::v1::handlers::{classes, computed_fields, events};
pub fn config(cfg: &mut web::ServiceConfig) {
    cfg.service(computed_fields::get_shared_computed_fields)
        .service(computed_fields::create_shared_computed_field)
        .service(computed_fields::patch_shared_computed_field)
        .service(computed_fields::delete_shared_computed_field)
        .service(computed_fields::preview_shared_computed_field)
        .service(computed_fields::rebuild_shared_computed_fields)
        .service(classes::get_classes)
        .service(classes::get_class)
        .service(events::get_class_events)
        .service(classes::get_class_history)
        .service(classes::get_class_as_of)
        .service(classes::create_class)
        .service(classes::update_class)
        .service(classes::delete_class)
        .service(classes::get_class_permissions)
        .service(classes::get_object_in_class)
        .service(events::get_object_events)
        .service(classes::get_object_history)
        .service(classes::get_object_as_of)
        .service(classes::get_objects_in_class)
        .service(classes::patch_object_in_class)
        .service(classes::delete_object_in_class)
        .service(classes::create_object_in_class)
        .service(classes::get_related_classes)
        .service(classes::get_related_class_relations)
        .service(classes::get_related_class_graph)
        .service(classes::delete_class_relation)
        .service(classes::create_class_relation)
        .service(classes::get_related_objects)
        .service(classes::get_related_object_relations)
        .service(classes::get_related_object_graph)
        .service(classes::get_object_relation_from_class_and_objects)
        .service(classes::delete_object_relation)
        .service(classes::create_object_relation);
}
